travis:
  secure:
    BINSTAR_TOKEN: huWIVOzeyibjeIXbqOpUzkIZ8PRwL8aGG06SLBBej1kehWpdLPCIgU78PhyvuAHYGdSIx8TtigZ7nC26W6p/6UCaQd0QzyDoePQeorbpa5LL8P8bUs1dfgLHYeegdBnGeFFwQFZRRDeEwvT+i4jmMOxAhnU4hlbXVxEbEU7FUDZTfpUj/mu5aIw5Eby1lseTXiqsjHVof64ZjpGRVIhf8v5N3/1L0m5ToBIUKuOkwwTuFIPguBzF/5vIIpPYGKPSxzmpx2rxDFp6cpVylHUlfGzyrFyyjENdBWk52OQsGm+uh+rt4DXwCyl4ijaqoFeoGg+VZHAUsFQN0j2/YYfAhENeour2OVq4cJDdZHJytsu7Rpvk+CZnUsMA18Bayp7j5xScLPF0iJjZfkufGle/kQA1OP5eX/ukhpVKyVy2dVvm/IL7gfiY1kfjdAPBd1CMLU7v0zIStzFyL4pXizhFhIp++D7nBkGgPwfdlmjsEPPjQ2dqeCc6IELO1BRNIlHtfMBu/Y8XM6hPIZiOeF0eONOttrwFvdy1QgO7Ssi9K5eJgH8284RUmewMupU1776/9yzqlNAOgUhqdJviOygfiEYlxNnpz+T2Qk6zMO5c3cMHOR/pVJ+RIKXFbrCNPzxNQGV3NxZCgA7yeyk95/7JhTFNKqdn2pxseY6vSa2IWyw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
